# ---
# - hosts: webservers
#   become: True
#   collections:
#     - nginxinc.nginx_core
#   tasks:
#     - name: Install NGINX
#       ansible.builtin.include_role:
#         name: nginx








---
- hosts: webservers 
  become: True
  tasks:
      - name: ensure nginx is at the latest version
        apt: name=nginx state=latest
      - name: start nginx
        service:
          name: nginx
          state: started
          
#   - hosts: all
#   collections:
#     - nginxinc.nginx_core
#   tasks:
#     - name: Install NGINX
#       ansible.builtin.include_role:
#         name: nginx





#     - name: Install packages
#       apt:
#         name: "apache2"
#         state: "present"
#     - name: Start Apache server
#       service:
#         name: apache2
#         state: started
#         enabled: True
#     - name: Deploy static website
#       copy:
#         src: index.html
#         dest: /var/www/html/
# ...


# ---
# - hosts: all
#   tasks:
#     - name: ensure nginx is at the latest version
#       apt: name=nginx state=latest
#     - name: start nginx
#       service:
#           name: nginx
#           state: started


# ---
# - hosts: all
#   collections:
#     - nginxinc.nginx_core
#   tasks:
#     - name: Install NGINX
#       ansible.builtin.include_role:
#         name: nginx